play_pattern_timed [0], [w]
play_pattern_timed [:C5, :C5, :Bb4, :C5, :G4, :F4, :G4], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:Eb5, :Eb5, :D5, :Eb5, :D5, :Bb4, :C5], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:C5, :C5, :Bb4, :C5, :G4, :F4, :G4], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:G5, :G5, :F5, :Eb5, :C5, :Bb4, :C5], [e, e, s, e, s+s, s, e+q]


play_pattern_timed [0, 0, :G4, :C5, :D5, :Eb5, :F5, :D5, :Eb5, :C5], [q, s, s, s, s, e, s, s+s, s, e]
play_pattern_timed [0], [w]
play_pattern_timed [0, 0, :Bb4, :Eb5, :F5, :G5, :Ab5, :F5, :G5, :Eb5], [q, s, s, s, s, e, s, s+s, s, e]
play_pattern_timed [:Eb5, :F5, :D5, :Eb5], [q_, e, q_, e]
play_pattern_timed [:C5], [w]
play_pattern_timed [:C5, :C5, :Bb4, :C5, :G4, :F4, :G4], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:G5, :G5, :F5, :Eb5, :C5, :Bb4, :C5], [e, e, s, e, s+s, s, e+q]

play_pattern_timed [0], [w]
play_pattern_timed [:C5, :C5, :Bb4, :C5, :G4, :F4, :G4], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:Eb5, :Eb5, :D5, :Eb5, :D5, :Bb4, :C5], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:C5, :C5, :Bb4, :C5, :G4, :F4, :G4], [e, e, s, e, s+s, s, e+q]
play_pattern_timed [0], [w]
play_pattern_timed [:G5, :G5, :F5, :Eb5, :C5, :Bb4, :C5], [e, e, s, e, s+s, s, e+q]